# # 垂直候选列表
# Vertical Candidate List=False
#
# # 按屏幕 DPI 使用
# # PerScreenDPI=True
#
# # Font
# Font="Noto Sans 12"
#
# # 主题
# Theme=winter

Vertical Candidate List=False
PerScreenDPI=True
Font="Smartisan Compact CNS 13"
Theme="macOS-light"
